In [1]:
import numpy as np

## Creating Numpy Arrays from Python Lists

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
[3.14,4,2,3]

[3.14, 4, 2, 3]

In [4]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a1 = np.array([1,2,3,4])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],
              [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(a2)

numpy.ndarray

In [10]:
a2.shape

(2, 3)

In [11]:
a2.ndim

2

In [12]:
a2.dtype

dtype('int32')

In [13]:
a2.size #Tổng element của ma trận a2

6

In [14]:
print("***-----***")

***-----***


## Creating Numpy Arrays from Scratch

### `zeros`  `ones`  `full`  `arange`  `linspace`

In [15]:
b = np.zeros([2,3], dtype='int')
print(b)
print(b.dtype)

[[0 0 0]
 [0 0 0]]
int32


In [16]:
b = np.ones([3,5])
print(b)
print(b.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64


In [17]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (This is similar to the built-in range() function)

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [19]:
# Create an array of 5 values evenly spaced between 0 and 1

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### `random`

In [20]:
np.random.random((4,4))

array([[0.37255588, 0.41290044, 0.342912  , 0.87550174],
       [0.66954576, 0.63429085, 0.16644499, 0.03602033],
       [0.30020867, 0.13191533, 0.12552472, 0.57105652],
       [0.83922577, 0.42434539, 0.02819456, 0.75945726]])

In [21]:
np.random.random((4,4))

array([[0.38737117, 0.01557927, 0.35885891, 0.08402094],
       [0.85301793, 0.79708065, 0.73772769, 0.05098194],
       [0.801543  , 0.42943613, 0.36802365, 0.79589095],
       [0.3386698 , 0.79728787, 0.21722659, 0.50700548]])

In [22]:
# Seed for reproducibility

np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [23]:
np.random.normal(0, 1, (3,3)) #(min, standard-deviation, size-matrix)

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [24]:
np.random.randint(0,10,(4,5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

In [25]:
np.random.rand(4,4)

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 , 0.6235101 ]])

## Array Indexing & Slicing

### One-dimensional subarray

In [26]:
x1 = np.random.randint(20, size = 6)
x1

array([15, 13, 16, 17,  5,  9])

In [27]:
x1[3], x1[0], x1[-1]

(17, 15, 9)

### Multi-dimensional array

In [28]:
x2 = np.random.randint(10, size=(3,4))
x2

array([[3, 0, 5, 0],
       [1, 2, 4, 2],
       [0, 3, 2, 0]])

In [29]:
x2[1,2]

4

In [30]:
x2[1,2] = 6

In [31]:
x2

array([[3, 0, 5, 0],
       [1, 2, 6, 2],
       [0, 3, 2, 0]])

### Slicing:
#### `x[start : stop : step]`

In [32]:
x1

array([15, 13, 16, 17,  5,  9])

In [33]:
x1[0:3] #Lấy khoảng cần lấy

array([15, 13, 16])

In [34]:
# every other element, every 2 step
x1[::2]

array([15, 16,  5])

In [35]:
x2

array([[3, 0, 5, 0],
       [1, 2, 6, 2],
       [0, 3, 2, 0]])

In [36]:
# 2 rows, 3 columns
x2[:2, :3]

array([[3, 0, 5],
       [1, 2, 6]])

In [37]:
x2[:, :2]

array([[3, 0],
       [1, 2],
       [0, 3]])

## Reshaping of Arrays & Tranpose

In [38]:
grid = np.arange(1,10)
grid.shape

(9,)

In [40]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
x = np.array([1,2,3])

In [43]:
x.shape

(3,)

In [49]:
x.reshape((1,3)).shape

(1, 3)

In [53]:
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [54]:
x.T

array([[1, 3],
       [2, 4]])

## Array Concatenation and Splitting

In [55]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [59]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [60]:
grid = np.array([[1,2,3],
                [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.concatenate((grid,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [62]:
np.concatenate((grid,grid), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [67]:
# vertically stack
x = np.array([1,2,3])

grid = np.array([[9,8,7],
                [6,5,4]])

In [65]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [68]:
# horizontally stack the arrays: hstack
y = np.array([[99], [99]])

np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

### Splitting of arrays

In [69]:
x = np.array([1,2,3, 99, 69, 3,2,1])

In [75]:
x1, x2, x3 = np.split(x,[3,5])

In [76]:
print(x1,"\n",x2,"\n",x3)

[1 2 3] 
 [99 69] 
 [3 2 1]


## Broadcasting of Vectorized operations

In [77]:
a = np.arange(3)

In [78]:
a

array([0, 1, 2])

In [79]:
a+5 #broadcasting

array([5, 6, 7])

In [81]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [82]:
a.shape, b.shape

((3,), (3, 3))

In [83]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [85]:
a * b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [88]:
c = np.arange(3).reshape((3,1))

In [90]:
c

array([[0],
       [1],
       [2]])

In [91]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Manipulating & Comparing Arrays

### Aggregation
- Aggregation = performing the same operation on a number of things

In [99]:
list_number=[1,2,3]

In [100]:
ll = np.array(list_number)

In [101]:
ll.shape

(3,)

In [104]:
sum(ll) #Python sum()

6

In [105]:
np.sum(ll) #Numpy sum()

6

In [110]:
#Create a massive Numpy array

massive_array = np.random.random(10000)
massive_array[:5]

array([0.39270934, 0.45369961, 0.60153853, 0.93240954, 0.47088361])

In [111]:
massive_array.shape

(10000,)

In [113]:
%timeit sum(massive_array) #Python built-in function sum()
%timeit np.sum(massive_array) #Numpy's np.sum()

810 µs ± 2.76 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
5.62 µs ± 9.96 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [114]:
np.mean(massive_array)

0.5000875852672286

In [115]:
np.max(massive_array)

0.9999682163635668

In [116]:
np.min(massive_array)

0.00020009521859265522

In [117]:
dog_height = [600, 470, 170, 430, 300]
dog_height = np.array(dog_height)

np.std(dog_height)

147.32277488562318

In [118]:
np.var(dog_height)

21704.0

In [119]:
np.sqrt(np.var(dog_height))

147.32277488562318

## Sorting Arrays
- np.sort uses an quicksort algorithm

In [121]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [122]:
# A related function is argsort, which instead returns the indices of the
# sorted elements
np.argsort(x) #Cho biết vị trí sort của phần tử

array([1, 0, 3, 2, 4], dtype=int64)

In [124]:
np.random.seed(42)

MatA = np.random.randint(0,10, size=(4,6))

In [125]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [126]:
np.sort(MatA, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [127]:
np.sort(MatA, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Linear Algebra

In [129]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[6,5],
             [4,3],
             [2,1]])

In [132]:
# A(3x3) dot product B(3x2)

A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [133]:
B.T #(2x3)

array([[6, 4, 2],
       [5, 3, 1]])

In [134]:
B.T@A # ~ B transpose .dot(A)

array([[36, 48, 60],
       [24, 33, 42]])

In [139]:
#Or
C = np.transpose(B).dot(A)
C

array([[36, 48, 60],
       [24, 33, 42]])

### Dot Product Example

In [142]:
#Number of jars sold
np.random.seed(0)

sales_amounts = np.random.randint(20, size=(5,3))

In [143]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [145]:
#Create weekly_sales DataFrame
import pandas as pd

weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"],
                                           columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [146]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [155]:
# Create a price array

prices = np.array([10, 8, 12])
prices.shape

(3,)

In [152]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ['Price'], columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [153]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [157]:
weekly_sales.shape, butter_prices.T.shape

((5, 3), (3, 1))

In [158]:
total_prices = weekly_sales.dot(butter_prices.T)

In [159]:
weekly_sales["Total Price"] = total_prices
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Price
Mon               12             15              0          240
Tues               3              3              7          138
Wed                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142